# CircleCI v2.1 Config
version: 2.1

##
# orbs
#
# Orbs used in this pipeline
###
orbs:
  anchore: anchore/anchore-engine@1.6.0
  slack: circleci/slack@3.4.2

##
# defaults
#
# YAML defaults templates, in alphabetical order
##
defaults_Dependencies: &defaults_Dependencies |
  apk --no-cache add git ca-certificates curl openssh-client bash
  apk add --no-cache -t build-dependencies make gcc g++ python libtool autoconf automake
  npm config set unsafe-perm true
  npm install -g node-gyp
  # add github to known hosts
  mkdir -p ~/.ssh/
  ssh-keyscan github.com >> ~/.ssh/known_hosts
  # set up destination dirs
  mkdir -p /tmp/repos
  mkdir -p /tmp/results

defaults_awsCliDependencies: &defaults_awsCliDependencies |
  apk upgrade --no-cache
  apk --no-cache add \
          python3 \
          py3-pip \
          groff \
          less \
          mailcap
  pip3 install --upgrade pip awscli==1.14.5 s3cmd==2.0.1 python-magic

##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: /home/circleci/project/
    docker:
      - image: node:12.16.0-alpine

  default-machine:
    machine:
      image: ubuntu-1604:201903-01

##
# Jobs
#
# A map of CircleCI jobs
##
jobs:
  setup:
    executor: default-docker
    steps:
      - checkout
      - run:
          name: Install general dependencies
          command: *defaults_Dependencies
      - run:
          name: Access npm folder as root
          command: cd $(npm root -g)/npm
      - run:
          name: Update NPM install
          command: cd oss-stats && npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "oss-stats/package-lock.json" }}
          paths:
            - oss-stats/node_modules
  
  # A set of scans based on cloned repos
  repo-tools:
    executor: default-docker
    steps:
      - checkout
      - run: 
          name: Define custom environment variables
          command: |
            echo 'export GET_REPO_PATH=/tmp/results/repos_filtered.json' >> $BASH_ENV
            echo 'export REPO_LIST_OVERRIDE_PATH=/tmp/results/repos_filtered.json' >> $BASH_ENV
      - run:
          name: Install general dependencies
          command: *defaults_Dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "oss-stats/package-lock.json" }}
      - run:
          name: Get the updated list of repos
          command: |
            cd ./oss-stats && npx gulp get-repo-json
            # convert to a csv for easy reference later on
            cat /tmp/results/repos_filtered.json | jq -r ".[]" | sort > /tmp/results/repos_filtered.csv
      - run:
          name: Run the cloc tool
          command: |
            cd ./oss-stats && npx gulp lines
      - run:
          name: Run the dependencies tool
          command: |
            cd ./oss-stats && npx gulp dependencies
  
  # A set of tools based on the github api
  github-api-tools:
    executor: default-docker
    steps:
      - checkout
      - run: 
          name: Define custom environment variables
          command: |
            echo 'export GET_REPO_PATH=/tmp/results/repos_filtered.json' >> $BASH_ENV
            echo 'export REPO_LIST_OVERRIDE_PATH=/tmp/results/repos_filtered.json' >> $BASH_ENV
      - run:
          name: Install general dependencies
          command: *defaults_Dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "oss-stats/package-lock.json" }}
      - run:
          name: Get the updated list of repos
          command: |
            cd ./oss-stats && npx gulp get-repo-json
            echo "GET_REPO_PATH is ${GET_REPO_PATH}"
            # convert to a csv for easy reference later on
            cat /tmp/results/repos_filtered.json | jq -r ".[]" | sort > /tmp/results/repos_filtered.csv
      - run:
          name: Run the contributors tool
          command: |
            echo "REPO_LIST_OVERRIDE_PATH is ${REPO_LIST_OVERRIDE_PATH}"
            cd ./oss-stats && npx gulp contributors
      - run:
          name: Run the commits tool
          command: |
            cd ./oss-stats && npx gulp commits
      # This is useful for the spreadsheet, but we need to make sure it matches the list we use to evaluate repos
      - run:
          name: Run the repos tool
          command: |
            cd ./oss-stats && npx gulp get-repo-csv
      - store_artifacts:
          path: /tmp/results/


##
# Workflows
#
# CircleCI Workflow config
##
workflows:
  version: 2
  run_monthly:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - setup:
          context: org-global
      - repo-tools:
          context: org-global
          requires:
            - setup
      - github-api-tools:
          context: org-global
          requires:
            - setup

  run_on_commit:
    jobs:
      - setup:
          context: org-global
      - repo-tools:
          context: org-global
          requires:
            - setup
      - github-api-tools:
          context: org-global
          requires:
            - setup
          
          