/**
 * A list of all repos which should be skipped by the UpdateLicense tool
 */

export default [

  //The following need a different license
  'mojaloop.github.io',
  'docs', //Docs has a different license

  // The following are deprecated repos
  'dfsp-ledger',
  'dfsp-mock',
  'dfsp-account',
  'dfsp-api',
  'dfsp-admin',
  'dfsp-identity',
  'dfsp-transfer',
  'dfsp-subscription',
  'dfsp-rule',
  'dfsp-ussd',
  'dfsp-directory',
  'interop-elk',
  'ilp-service',
  'mock-pathfinder',
  'pathfinder-provisioning-client',
  'pathfinder-query-client',
  'interop-devops',

  // TODO:
  'helm',
  'dfsp-scheme-adapter',
  'project',
  'interop-switch',
  'test-scripts',
  'interop-ilp-conditions',
  'ml-api-adapter',
  'mojaloop-specification',
  'ntpd',
  'central-settlement',
  'deploy-config',
  'postman',
  'simulator',
  'ilp-crypto',
  'email-notifier',
  'central-event-processor',
  'central-services-metrics',
  'central-services-stream',
  'cross-network',
  'interop-switch-js',
  'ml-qa-regression-testing',
  'account-lookup-service',
  'documentation',
  'als-oracle-template',
  'terminal-integration',
  'hackathon',
  'als-oracle-account',
  'aws-iac',
  'wso2apim',
  'wso2iskm',
  'wso2-helm-charts',
  'wso2-extensions',
  'sdk-standard-components',
  'sdk-scheme-adapter',
  'als-oracle-pathfinder',
  'design-authority',
  'quoting-service',
  'documentation-artifacts',
  'event-sdk',
  'event-sidecar',
  'license-scanner',
  'transaction-requests-service',
  'event-stream-processor',
  'template-repo-public',
  'central-object-store',
  'apm-agent-nodejs',
  'opentracing-javascript',
  'apm-agent-nodejs-opentracing',
  'wso2-mysql',
  'wso2-comp',
  'sdk-mock-dfsp-backend',
  'central-services-health',
  'bulk-api-adapter',
  'template-typescript-public',
  'mojaloop-simulator',
  'api-notifier',
  'connection-manager',
  'postman-dev',
  'ml-number',
  'iac-lab',
  'workbench-media',
  'central-services-logger',
  'libpathfinder',
  'workbenches-woccu',
  'finance-portal-ui',
  'settlement-management',
  'operator-settlement',
  'pi8-perf-testing',
  'finance-portal-lib',
  'mojaloop-business-docs',
  'finance-portal-backend-service',
  'oracle-shared-library',
  'ml-self-testing-toolkit',
  'ml-self-testing-toolkit-ui',
  'archived',
  'LPS-Adapter',
]