
/* 
  A list of all repos to scan (non-exhaustive)
*/
// const repos = [
//   "documentation",
  // "central-ledger",
  // "helm",
  // "postman",
  // "ml-api-adapter",
  // "mojaloop-specification",
  // "central-settlement",
  // "simulator",
  // "account-lookup-service",
  // "sdk-scheme-adapter",
  // "central-services-shared",
  // "quoting-service",
  // "sdk-standard-components",
  // "mojaloop-simulator",
  // "ml-testing-toolkit",
  // "central-event-processor",
  // "transaction-requests-service",
  // "central-services-error-handling",
  // "email-notifier",
  // "bulk-api-adapter",
  // "database-lib",
  // "central-services-stream",
  // "project",
  // "ml-testing-toolkit-ui",
  // "central-services-metrics",
  // "event-sidecar",
  // "mojaloop-business-docs",
  // "event-sdk",
  // "central-services-logger",
  // "pisp-project",
  // "auth-service",
  // "event-stream-processor",
  // "testing-toolkit-test-cases",
  // "object-store-lib",
  // "central-services-health",
  // "api-snippets",
  // "contrib-pisp-demo-svc",
  // "thirdparty-sdk",
  // "sdk-mock-dfsp-backend",
  // "ml-testing-toolkit-shared-lib",
  // "contrib-cross-network-demo",
  // "license-scanner-tool",
  // "thirdparty-api-svc",
  // "contrib-pisp-demo-ui",
  // "reference-architecture-doc",
  // "contrib-pos-demo",
  // "ml-number",
  // "finance-portal-ui",
  // "settlement-management",
  // "operator-settlement",
  // "ci-config",
  // "contrib-fido2-flutter-lib",
  // "typescript-svc-template",
  // "finance-portal-backend-service",
  // "hackathon-docs",
  // "finance-portal-v2-ui",
  // "reporting-events-processor-svc",
  // "role-assignment-service",
  // "reporting-hub-bop-role-ui",
  // "reporting-hub-bop-settlements-ui",
  // "reporting-hub-bop-positions-ui",
  // "reporting-k8s-templates",
  // "mojaloop.github.io",
  // "design-authority-project",
  // "finance-portal-lib",
  // "oracle-shared-library",
  // "ml-schema-validator",
  // "reporting",
  // "iac-aws-backend",
  // "als-consent-oracle",
  // "iac-aws-platform",
  // "reporting-hub-bop-trx-ui",
  // "charts",
  // "business-operations-framework-docs",
  // "reporting-hub-bop-shell",
  // "logging-bc",
  // "ml-oss-sandbox",
  // "reporting-hub-bop-experience-api-svc",
  // "platform-shared-tools",
  // "community-tools",
  // "mojaloop-adapter",
  // "simulator-kafka",
  // "poc-architecture",
  // "contrib-rancher-scaler-tool",
  // "image-watcher-svc",
  // "iac-aws-bootstrap",
  // "iac-shared-modules",
  // "security-role-perm-operator-svc",
  // "microfrontend-shell-boilerplate",
  // "contrib-fido-test-ui",
  // "security-kratos-oidc-provider-ui",
  // "platform-shared-lib",
  // "auditing-bc",
  // "platform-configuration-bc",
  // "security-rbac-tests",
  // "security-bc",
  // "participants-bc",
  // "settlements-bc",
  // "accounts-and-balances-bc",
  // "ml-testing-toolkit-client-lib",
  // "account-lookup-bc",
  // "interop-apis-bc",
  // "gsp-connector",
  // "ml-operator",
  // "contrib-mojawallet-demo",
  // "ml-iso-hackathon",
  // "contrib-dev-portal",
  // "wso2is-populate",
  // "reporting-hub-bop-api-svc",
  // "microfrontend-boilerplate",
  // ".github",
  // "typescript-bc-template",
  // "testpages",
  // "haproxy-helm-charts",
  // "node-version-checker",
  // "scheduling-bc",
  // "vuepress-plugin-versioning",
  // "reporting-bc",
  // "transfers-bc",
  // "ml-core-test-harness",
  // "ml-pisp-bootcamp",
  // "quoting-bc"
// ]

//Core repos only!
const repos = [
  "account-lookup-bc",
  "account-lookup-service",
  "accounts-and-balances-bc",
  "alias-oracle",
  "als-consent-oracle",
  "als-oracle-pathfinder",
  "api-snippets",
  "auditing-bc",
  "auth-service",
  "beneficiary-management-system-svc",
  "beneficiary-registration-portal-backend",
  "beneficiary-registration-portal-frontend",
  "bulk-api-adapter",
  "business-operations-framework-docs",
  "callback-handler-simulator-svc",
  "central-event-processor",
  "central-ledger",
  "central-services-error-handling",
  "central-services-health",
  "central-services-logger",
  "central-services-metrics",
  "central-services-shared",
  "central-services-stream",
  "central-settlement",
  "cert-management-bc",
  "charts",
  "ci-config",
  "ci-config-orb-build",
  "community-tools",
  "contrib-cross-network-demo",
  "contrib-fido-test-ui",
  "contrib-fido2-flutter-lib",
  // "contrib-firebase-simulator",
  "contrib-mojawallet-demo",
  "contrib-pisp-demo-svc",
  "contrib-pisp-demo-ui",
  "contrib-pos-demo",
  "contrib-rancher-scaler-tool",
  "control-center-util",
  "Currency-conversion",
  "database-lib",
  "documentation",
  "email-notifier",
  "event-sdk",
  "event-sidecar",
  "event-stream-processor",
  "finance-portal-backend-service",
  "finance-portal-lib",
  "finance-portal-ui",
  "finance-portal-v2-ui",
  "foreign-exchange-bc",
  "fx-converter-template",
  "gsp-connector",
  "hackathon-docs",
  "haproxy-helm-charts",
  "helm",
  "iac-ansible-collection-roles",
  "iac-aws-backend",
  "iac-aws-bootstrap",
  "iac-aws-platform",
  "iac-modules",
  // "iac-runner",
  "image-watcher-svc",
  "iac-shared-modules",
  // "iac-tests",
  "iacv2-docs",
  "interop-apis-bc",
  "iso-20022-docs",
  "license-scanner-tool",
  "logging-bc",
  "merchant-payment-docs",
  "merchant-registry-svc",
  // "mfi-account-oracle",
  "microfrontend-boilerplate",
  "microfrontend-shell-boilerplate",
  "mifos-core-connector-docs",
  "mifos-core-connector",
  "mini-loop",
  "ml-api-adapter",
  "ml-core-test-harness",
  "ml-inter-scheme-docs",
  "ml-iso-hackathon",
  "ml-mosip-integration",
  "ml-number",
  "ml-operator",
  "ml-oss-sandbox",
  "ml-schema-validator",
  "ml-testing-toolkit-client-lib",
  "ml-testing-toolkit-shared-lib",
  "ml-testing-toolkit-ui",
  "ml-testing-toolkit",
  "mojaloop-adapter",
  "mojaloop-business-docs",
  "mojaloop-simulator",
  "mojaloop-specification",
  "mojaloop.github.io",
  "node-version-checker",
  "object-store-lib",
  "on-premises-deployment",
  "operator-settlement",
  "oracle-shared-library",
  "participants-bc",
  "payment-token-adapter",
  "payment-token-adapter",
  "pisp-project",
  "pisp-sig-docs",
  "pisp-ttk-sandbox",
  "platform-configuration-bc",
  "platform-shared-lib",
  "platform-shared-tools",
  "poc-architecture",
  "product-council",
  "quoting-bc",
  "quoting-service",
  "reference-architecture-doc",
  "reporting-bc",
  "reporting-events-processor-svc",
  "reporting-hub-bop-api-svc",
  "reporting-hub-bop-experience-api-svc",
  "reporting-hub-bop-positions-ui",
  "reporting-hub-bop-role-ui",
  "reporting-hub-bop-settlements-ui",
  "reporting-hub-bop-shell",
  "reporting-hub-bop-trx-ui",
  "reporting-k8s-templates",
  "reporting",
  "role-assignment-service",
  "scheduling-bc",
  "sdk-core-connector-openpayments-api-svc",
  "sdk-core-connector-rafiki-api-svc",
  "sdk-mock-dfsp-backend",
  "sdk-scheme-adapter",
  "sdk-standard-components",
  "security-bc",
  "security-kratos-oidc-provider-ui",
  "security-rbac-tests",
  "security-role-perm-operator-svc",
  "settlement-management",
  "settlements-bc",
  "simulator-kafka",
  "simulator",
  "testing-toolkit-test-cases",
  "thirdparty-api-bc",
  "thirdparty-api-svc",
  "thirdparty-sdk",
  "transaction-requests-service",
  "transfers-bc",
  "typescript-bc-template",
  "typescript-svc-template",
  "vault-agent-util",
  "vault-utils",
  "vn-helm"
]

// A list of repos that should be ignored from the stats
const ignoreList = [
  'archived',
  'als-oracle-account',
  'als-oracle-pathfinder',
  'als-oracle-template',
  'aws-iac',
  'apm-agent-nodejs',
  'apm-agent-nodejs-opentracing',
  'connection-manager',
  'cross-network',
  'design-authority',
  'deploy-config',
  'docs',
  'fraud_risk_management',
  'iac-lab',
  'iac_post_deploy',
  'mojaloop',
  'mojaloop-platform-iac',
  'ntpd',
  'opentracing-javascript',
  'pi8-perf-testing',
  'postman-dev',
  'test-scripts',
  'TIPS',
  'workbench-media',
  'wso2-helm-charts',
  'wso2-mysql',
  'wso2apim',
  'wso2iskm',
  'workbenches-woccu',
  'wso2-comp',
  'wso2-extensions',
  'wso2-helm-charts-simple',
]

export default {
  repos,
  ignoreList
}